### ISSUE TITLE
rpic Plugins funktionieren nicht

### ISSUE THREAD

**Issue by Akamaru** [Akamaru/Mikubot-V2#3]
Die Plugins [random_pic.lua](https://github.com/Akamaru/Mikubot-V2/blob/master/miku/plugins/random_pic.lua) und [random_pic_nsfw.lua](https://github.com/Akamaru/Mikubot-V2/blob/master/miku/plugins/random_pic_nsfw.lua) reagieren auf die Befehle, senden aber kein Bild.

**Comment by Brawl345** [comment]
Bei mir ging es mit nem Testpfad. Der Fix sollte helfen, ansonsten funktioniert das Plugin korrekt. Sind auch die Rechte richtig?

![bildschirmfoto vom 2016-09-12 00 55 33](https://cloud.githubusercontent.com/assets/5049892/18421187/c86768e2-7883-11e6-8e37-3b6b06fe8d86.png)

**Comment by Akamaru** [comment]
Sendet trotzdem nicht. Rechte passen.

**Comment by Akamaru** [comment]
#6
